# Generated by Django 3.2.3 on 2021-06-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfund',
            name='fund',
            field=models.FloatField(),
        ),
    ]
